name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to DigitalOcean
        run: |
          ssh root@134.122.123.133 "cd /var/www/html && git pull origin main && npm install && npm run build && systemctl restart nginx"

GITHUB_TOKEN: ${{ secrets.SSH_PRIVATE_KEY }}
